### ISSUE TITLE
Bug - Flip a Coin is not working.

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/EchaloASuerte#126]
Hi, I've upgraded the "production" application today, and after testing it a bit I noticed that the Coin wasn't working.

After a quick `git bisect` I've come to the conclusion that the commit that breaks it is: 4ee7f0cd74ba5dcb8d1d00a9eecb1d9a90843c92

I've tried to get to the bottom of this, but I failed to understand various parts of the code. I hope that this isn't only failing for me. 

To reproduce the bug:
- Go to http://92.222.219.42:8001/draw/coin/
- Click on the coin.

Expected output:
- Coin flipping and a result

Current output:
- Error 500
- Traceback from logs: http://paste.baserock.org/yepukabigi

**Comment by dnaranjo89** [comment]
Are you sure that you have the master there? I think this bug was already fixed. I don't get the error when I try locally (in master)

**Comment by palvarez89** [comment]
Then I guess we have to investigate why is this happening on the server: http://92.222.219.42:8001/draw/coin/

I'm 100% sure I'm using master, as I said, I was upgrading the server to use the latest version.

**Comment by dnaranjo89** [comment]
This bug is already corrected in the branch where the public draw is being implemented.

Further explanation: So far, based on the button pressed in a draw (toss, next or try) we perform the respective action in the server, since there is no "toss" button in the coinDraw, the JS code is not filling the hidden input "shared-type" and that's why it breaks

**Comment by palvarez89** [comment]
But I thought that the server defaults to toss if nothing was defined.

I'm OK if this being closed if it's already fixed in your branch. Thanks

**Comment by dnaranjo89** [comment]
The initialization of the field to "None" in form_base.py it's unnecessary and misleading (has already been removed in the new branch). This fields is not been rendered by the form but we do it manually in the template, so the initialization is useless there. 

Since in the POST the field is empty and the field in the model requires a value (which does since 963d28e6054d3cb0bd7e69b9d12415e695d97d4b) the initialization breaks

**Comment by palvarez89** [comment]
Good catch! I thought that the traceback of the logging was for something else :)

**Comment by Mariocj89** [comment]
@dnaranjo89  is this fixed already?

**Comment by palvarez89** [comment]
Last time I checked, it was fixed.
